source 'https://github.com/CocoaPods/Specs.git'

target 'ROCardToss', :exclusive => true do
  pod "ROCardToss", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "ROCardToss", :path => "../"

  
end
